---
title: "Lab 1"
author: "Juhyun Kim, Brendon Chau, Hua Zhou"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. SSH client on MacOS and Windows. 
    - MacOS: just open the `Terminal` app.  
    - Windows: download and install [`Git for Windows` aka `Git Bash`](https://gitforwindows.org). Accept default settings during the installation process.  This gives you a bash shell within Windows, which is also equipped with Git commands.

2. Connect to the teaching server. On MacOS Terminal or Windows Git Bash:  
    ```
    ssh username@server.ucla-biostat-203b.com
    ```
If you cannot connect, you may not have an account. Ask TA or instructor for help.

3. Change password on teaching server
    ```
    passwd
    ```

4. On teaching server, you can obtain a copy of the course material using git:  
    ```
    git clone https://github.com/ucla-biostat203b-2020winter/ucla-biostat203b-2020winter.github.io.git
    ```
To reproduce commands in the [Linux lecture](https://ucla-biostat203b-2020winter.github.io/slides/02-linux/linux.html), make sure you are in the correct folder
    ```
    cd ~/ucla-biostat203b-2020winter.github.io.git/slides/02-linux
    ```

5. Check whether you already have SSH keys at default location. On Linux/MacOS terminal or Windows Git Bash:
    ```
    ls -al ~/.ssh
    ```
   
6. If no SSH keys yet, generate a pair of SSH RSA keys
    - Method 1: generate keys on MacOS Terminal or Windows Git Bash. Follow [instructions in lecture notes](https://ucla-biostat203b-2020winter.github.io/slides/02-linux/linux.html#steps-to-generate-keys).  
    - Method 2: Use RStudio to generate keys. Tools -> Global Options... -> Git/SVN. 
Using either method, make sure keys are in the default location `~/.ssh/`

7. Brendon: WSL for Windows.

8. Register an account on GitHub Student Developer Pack, **using ucla.edu email**. Send GitHub handle to Juhyun Kim.

9. Set up seemless SSH connection between (1) laptop, (2) teaching server, and (3) GitHub.

10. Intitialize a project from GitHub within RStudio.